database:
  sqlite:
    used: true
    path: ../store/fathom.db
  postgres:
    used: false
    user: ""
    password: ""
    host: ""
    port: ""
    dbName: ""
server:
  port: "8082"
  logging:
    loggers:
      - charmLog
      - slog
    level: info
